### ISSUE TITLE
[ABI] Fix negative integers so that they actually return negative integers

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#115]
Currently we get this: 

`-3` 

when translated gives us

`115792089237316195423570985008687907853269984665640564039457584007913129639933`

this is the total amount a uint can hold - 3. This should be changed to reflect the case of an int type.

**Comment by compleatang** [comment]
have changed app11-negative_numbers to return negatives. as a base for testing, the asserts in the epm.yaml of that app should be uncommented out. this needs to get prioritized.

**Comment by compleatang** [comment]
please look into this issue now that the abi issues are sorted.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1026](https://github.com/eris-ltd/eris-cli/issues/1026) via [**ZenHub**](https://www.zenhub.com/)
