### ISSUE TITLE
[Bundle Management] epm init feature

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#121]
In order to create a "bundle"/"package", there should be a command that creates the epm.yaml file, a CMC (contract managing contract), and a readme.md inside of the current working directory.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1017](https://github.com/eris-ltd/eris-cli/issues/1017) via [**ZenHub**](https://www.zenhub.com/)
