### ISSUE TITLE
EPM needs a way to smoothly handle events

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#124]
I think we will need a way to set up a "watcher" on our job file for whenever an event is hit, and to specify jobs to run should an event be hit, or specify a location to dump the data gotten from an event. Filtering should also be enabled. One would think that this event would be specified right after the contract is deployed. This one will be very tricky to get right. I need suggestions here.  I have something of an idea but I want to hear what others suggest first.

**Comment by compleatang** [comment]
This would add a lot of overhead to epm in terms of websockets infrastructure. What is the problem this would solve and do users actually have that problem and is epm the right place to solve it?

**Comment by VoR0220** [comment]
In the context of the epm.yaml, it simply opens up all features of solidity to be available in the case of a set of jobs being performed. In the EVM, it enables use of the logging functionality. Hell you might be able to go ahead and "debug" your contract in a way by logging output from the chain amongst other precious forms of data. I don't understand why we would enable people to run jobs on a certain set of features of the language and leave out others.

**Comment by compleatang** [comment]
That's not really a problem/solution. That's just a nice to have. We can reopen this later if an actual user problem is confronted.
