### ISSUE TITLE
[Tests] Named Testing and Reuse of testing folders

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#130]
It's tedious to go and create numerous contracts to test many of the same values as before...I think a better method for testing would be to categorize the tests/packages by what they actually handle, and just continue to add onto the contract/s in the directory and continue to write onto the epm.yaml. It saves us a bunch of time with testing and test development.

**Comment by compleatang** [comment]
intertwining our test fixtures is not a good idea. it makes them less modular and makes us run the whole test suite rather than a single test fixture. i'm not keen on this unless there are better arguments than "it's tedious".

**Comment by VoR0220** [comment]
So to an extent I agree with you, but I think that's easier to solve by just writing things off of one epm.yaml and splitting that into parts by jobs and group them from there. It retains modularity, it's just defining it at a finer level imo. Mostly it enables using base contracts instead of copying numerous different base contracts over and over.
