### ISSUE TITLE
EPM test fails on valid contract code

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#131]
The epm.yaml test in this directory fails: https://github.com/eris-ltd/eris-contracts-bundles/tree/develop/src/commons-collections
However, the attached [Test.zip](https://github.com/eris-ltd/eris-pm/files/266648/Test.zip)
contains a contract and test that use the exact same source code copied out of the Bytes32ToAddressMapper.sol and the test succeeds. This shows that the contract code generally works and there might something wrong on the Eris side. This needs to be investigated.

To reproduce:
- Checkout the develop branch of the eris-contracts-bundles repo
- Change to the `src/commons-collections` directory
- Copy the dependencies: `cp ../commons-base/*.sol ./com/erisindustries/commons-base/`
- run `eris pkgs do ...` against a local chain

- [x] `docker version`: 1.10.3
- [x] `eris version`: 0.11.4
- [x] `go version` (if applicable): go1.6.2 darwin/amd64
- [x] `docker-machine version` (if applicable / !linux): version 0.6.0, build e27fb87
- [x] operating system details (osx/windows/linux): OSX (El Capitan)

**Comment by compleatang** [comment]
confirmed still failing.

**Comment by compleatang** [comment]
this is a super strange error. changing those query-contracts (in the closed source contract) to calls **without** a wait gives me the same result as the query-contract but performing them **with** a wait gives the correct result.

**Comment by compleatang** [comment]
altho not a solidity expert i think forcing the change from query-contracts to call is desired behaviour cause of this line no? -> https://github.com/eris-ltd/eris-contract-bundles/blob/develop/src/commons-base/Owned.sol#L10

**Comment by VoR0220** [comment]
...oh I always add a wait...Idek why wait is an option if I'm tbh. Unless you're trying to do something in parallel or something, maybe?

**Comment by compleatang** [comment]
calls without wait are meant for flooding and parallel execution scenarios when the result/return doesn't matter. here the return mattered to get the information i needed. however it was the msg.sender in that line referenced which required this to be a call not a query-contract. the wait was largely irrelevant other than to get the information i needed out.

**Comment by compleatang** [comment]
closing this issue as the tests appear fixed.
