### ISSUE TITLE
"Index out of range" when invoking function with address

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#134]
The attached contracts and epm.yaml can be used to reproduce a "index out of range" exception in the go code. The resulting log and stacktrace are also attached.

- [x] `docker version`: 0.11.1
- [x] `eris version`: 0.11.4
- [x] `go version` (if applicable): go1.6.2 darwin/amd64
- [x] `docker-machine version`: 0.7.0, build a650a40
- [x] operating system details: OSX

**Comment by j-h-scheufen** [comment]
[stacktrace.txt](https://github.com/eris-ltd/eris-pm/files/273535/stacktrace.txt)

[contracts.zip](https://github.com/eris-ltd/eris-pm/files/273538/contracts.zip)

**Comment by compleatang** [comment]
@VoR0220 where are we here?

**Comment by compleatang** [comment]
the abi rework should have fixed this. reopen if it reappears.
