### ISSUE TITLE
[Core] Clear out old tendermint dependencies

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#135]
@silasdavis @benjaminbollen The current tendermint and mint-client dependencies will be in the following links:

https://github.com/eris-ltd/eris-pm/blob/develop/perform/jobs_test_jobs.go#L48-L49

https://github.com/eris-ltd/eris-pm/blob/develop/util/writers.go#L128

https://github.com/eris-ltd/eris-pm/blob/develop/perform/jobs_transact.go#L327

https://github.com/eris-ltd/eris-pm/blob/develop/perform/jobs_contracts.go#L313

https://github.com/eris-ltd/eris-pm/blob/bc88163de4ebae7e039ecd0e8ea2b36592171185/perform/jobs_contracts.go#L179

https://github.com/eris-ltd/eris-pm/blob/master/cmd/config.go#L6

Let me know what these would translate to in EDB.

**Comment by compleatang** [comment]
this is down now, no?

**Comment by VoR0220** [comment]
Yes
