### ISSUE TITLE
[ABI] Redo PreProcess function

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#136]
Reasons to do this:

a) it's ugly as sin
b) it's inefficient, I think we might do better with a string map
c) it's very difficult to determine what is going on in the function, even from someone who has dissected it before.

**Comment by compleatang** [comment]
can we close this?

**Comment by VoR0220** [comment]
no not yet. It is still very much a todo.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1034](https://github.com/eris-ltd/eris-cli/issues/1034) via [**ZenHub**](https://www.zenhub.com/)
