### ISSUE TITLE
Solc compile error is not forwarded and instead leads to `encoding/hex: odd length hex string`

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#160]
For the attached contract ([Archive.zip](https://github.com/eris-ltd/eris-pm/files/352287/Archive.zip)), the solidity compiler would return a compile error (tested with https://ethereum.github.io/browser-solidity):
```
Untitled:10:9: Warning: Uninitialized storage pointer. Did you mean '<type> memory localVar'?
        TestStruct localVar;
        ^-----------------^
```
However, when compiling through EPM (see attached epm.yaml), the failure is returned as
```
$ eris pkgs do -c test -a 609DE71ECA4548D090757E63E69E62898D2D037F -l https://compilers.eris.industries:10113
Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
Executing Job                                 deployK
Error compiling contracts
encoding/hex: odd length hex string
```
Notice the use of the 0.11.3 compilers due to current problems with 0.12.0. It should be tested if the same symptoms occur with 0.12.0!

### Requirements
The EPM output should contain the solc output and present it to the user to support troubleshooting.

Versions:
```
OSX version: 10.11.5
Eris CLI Version: 0.12.0
Docker:
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
docker-machine version 0.7.0, build a650a40
```

**Comment by VoR0220** [comment]
This should be closed with the advent of the RC2 refactor of the compilers...and the occasional restart of the 0.11.4 compilers.
