### ISSUE TITLE
failed to send HTTP request Post https://compilers.eris.industries:10114/compile: local error: internal error

### ISSUE THREAD

**Issue by bkrem** [eris-ltd/eris-pm#164]
Running my usual 
```
eris pkgs do --chain simplechain --address C005C16874722B35AC4EA353DAE793CDE2F65489
```
 has been returning the following error since yesterday (here shown using the `--verbose` flag):

```
Hello! I'm EPM.
Using Compiler at                             https://compilers.eris.industries:10114
Using Chain at                                http://chain:46657/
Using Signer at                               http://keys:4767
Using ChainID from Node                       simplechain
Loading eris-pm Package Definition File.
Executing Job                                 defaultAddr
Type                                          Account
Setting Account                               C005C16874722B35AC4EA353DAE793CDE2F65489
Getting Public Key                       from=http://keys:4767
Executing Job                                 TaskManager
Type                                          Deploy
Contract path                                 TaskManager.sol
Setting compiler path                         https://compilers.eris.industries:10114
Language to use                               sol
failed to send HTTP request Post https://compilers.eris.industries:10114/compile: local error: internal error
Error compiling contracts
Post https://compilers.eris.industries:10114/compile: local error: internal error
```

The error seems somewhat ambiguous since it doesn't return a status code for the attempted POST request. Is this an issue server-side or could this be an issue with my local `eris` having been corrupted?
The contract I'm deploying did not change between the last time the deployment worked and the error occurring.

---

- [x] `docker version` 1.11.2
- [x] `eris version` 0.11.4
- [x] `docker-machine version` 0.7.0
- [x] operating system details OSX El Capitan v10.11 beta seed

**Comment by bkrem** [comment]
Ok, after a lot of "chasing a black cat in a dark room"-type probing it turns out simply changing the port to `10113` (as shown in https://github.com/eris-ltd/eris-pm/issues/160) instead of the default `10114` does the trick: 

```
eris pkgs do --chain simplechain --address C005C16874722B35AC4EA353DAE793CDE2F65489 --compiler=https://compilers.eris.industries:10113
```

Contracts are compiled and then deployed as expected.

Is this an intentional change which should be reflected in the documentation or is there a different compiler version on each port, with the one on port `10114` currently returning a 5xx error?

**Comment by zramsay** [comment]
hi @bkrem we're in the process of sorting out a few problems with the compiler(s) that arose during the rc phase. Indeed, we could document some of these compiler workarounds better (it's not intentional)

**Comment by bkrem** [comment]
Thanks for clearing up that confusion @zramsay, this wouldn't have been a substantial issue in theory but the local compiler image wasn't behaving as documented at all so I'll open issues on the things I noticed there too. Would love to dive into the Go code myself and write PRs to fix the local one but I just don't have the time unfortunately :/

**Comment by VoR0220** [comment]
@bkrem are you still running into issues on 0.11.4 compilers?

**Comment by bkrem** [comment]
Compiles and deploys properly again on port `10114` (assuming that's the microservice for 0.11.4 from the port-semver similarity), thanks for fixing it :+1:!

I'll check the local Docker image again first thing tomorrow and file issues if there still are any.

I'd suggest you briefly document that other ports apart from `10114` are a viable fallback for devs in situations like this to save a lot of hair pulling. I'm happy to do it if someone lets me know where it is appropriate in the docs :)

**Comment by VoR0220** [comment]
I think I'm going to write a PR error for the client compiler to try to resolve this. But thanks for the suggestion! Are you in the slack per chance?

**Comment by bkrem** [comment]
Not so far, email is ben.kremer@protonmail.com . 
That would definitely make comms a lot simpler and avoid me opening unnecessary issue tickets if I can confirm unwanted behaviour with you guys first.

**Comment by VoR0220** [comment]
you've been sent an invite
