### ISSUE TITLE
non-standard log message from `eris pkgs do`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-pm#166]
![screenshot from 2016-07-20 01-21-52](https://cloud.githubusercontent.com/assets/8304391/16975848/5d267900-4e18-11e6-9974-c1df474cca02.png)

`INFO[0004] Hit UnpackProcessType`
^ seems to come from using the standard logging library rather than `eris-logger`

**Comment by VoR0220** [comment]
yeah I noticed that recently, and I have no clue what's causing it. I searched for it and I can't seem to find it.

**Comment by VoR0220** [comment]
solved by #177
