### ISSUE TITLE
[Core] Better meld the architecture in terms of call and query

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#179]
Problem: There's a decent chunk of duplicated code in queryContract job and callContract job. The only difference between these two is that one is simulated and one is actually enacted. 

Solution: I propose that we either create an interface between these two such that they have access to the methods they require while still keeping themselves separate. This would also help to keep the architecture relatively clean.

**Comment by compleatang** [comment]
revisit post merger and other changes.
