### ISSUE TITLE
auto set to running chain and/or create a default chain to deploy to

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#181]
Problem: It's a pain to have to constantly say what chain you're deploying to in either epm or eris pkgs do. 

Solution: Either make some opinionated assumptions or allow these to be set by the user either in a separate toml file or in the epm.yaml itself. This idea is far down the line but I'm imagining in the case of the former that if there is only one running chain that eris cli should be smart enough to determine that that is the chain that you want to deploy to (because it is the only one running). Another way we could simplify the process is right before the jobs description in the epm.yaml we go ahead and we define what chain we want this to be deployed on. This might run into problems from the package management side however. In any case I definitely feel it is worth discussing.

**Comment by compleatang** [comment]
this is a cli feature and there is an issue for it in there already.
