### ISSUE TITLE
Clean Vendor of Non essential Geth packages

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#183]
Problem: Geth is a bloated monolith, but contains essential packages for operation with the ABI. During the port to glide, we've seen the image size triple due to geth. There is a glide vendor cleaner plugin, however, it doesn't play nicely with and deletes C Go files which then cause problems in the crypto package. 

Solution: Either fix the vendor clean plugin or we have to hack a solution together ourselves. This is a tricky one.

**Comment by compleatang** [comment]
epm's image since is *way* too big.... an alpine based one binary image should not be bigger than a ubuntu based image with apt-get installed binaries! ....

```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
quay.io/eris/data        0.12.0-rc3          9c679a4c4834        3 days ago          218.6 MB
quay.io/eris/epm         0.12.0-rc3          8349a7620608        4 days ago          1.08 GB
quay.io/eris/compilers   latest              ee4f9e13c24c        5 days ago          1.017 GB
```

**Comment by AFDudley** [comment]
Properly running `make install` for geth should resolve this issue. If they don't allow for that, we can do it, I should walk @VoR0220 through it and it should take us less than a hour via screen share.

**Comment by VoR0220** [comment]
I believe my vendor clean solution has worked. I need to check on it. When last i ran the tests everything was running swimmingly.
