### ISSUE TITLE
[Tests] Implement integration test for deep-nested contract creation

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-pm#189]
- `eris version 0.11.4`
- https://github.com/eris-ltd/eris-db/issues/164 raised failure on deeply nested contract creation
- [ ] problem has been isolated and fixed (0.11.4 https://github.com/eris-ltd/eris-db/pull/184; 0.12.0 https://github.com/eris-ltd/eris-db/issues/205) 
- [ ] integrate test code for eris-pm attached in https://github.com/eris-ltd/eris-db/issues/164

**Comment by compleatang** [comment]
fixed by libs tests.
