### ISSUE TITLE
[Tests] Bytes32 Tests for Cryptographic functions

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#192]
Problem: These tests currently do not exist and yet they are often used by our users and I think are actually necessary to working with smart contracts. 

Solution: Write tests for them and write to the tests.

**Comment by benjaminbollen** [comment]
Can we raise the priority for this though?
E-PM does not display 32 bytes; rather 32 characters potentially.

**Comment by compleatang** [comment]
Won't make 0.12.0 but am fine adding to 0.12.1

**Comment by VoR0220** [comment]
I agree this should be in 0.12.1

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1030](https://github.com/eris-ltd/eris-cli/issues/1030) via [**ZenHub**](https://www.zenhub.com/)
