### ISSUE TITLE
[Core] Support multiple output files for EPM pkgs command

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#195]
The change implemented in https://github.com/eris-ltd/eris-pm/issues/176 does not go far enough to support the needs of users who manage their epm jobs in multiple files. Currently EPM supports the `-f` flag which allows users to organize their jobs across multiple files; this is very useful and a requirement for bundles deployment, e.g. to be able to deploy contracts in separate phases, like libraries. However, it is currently not possible to control the output file and as far as I can see, the `jobs_output.json` would be overwritten on sequential jobs invocation.

## Requirements
1. Change the default behavior to use the input filename as a template for the output. `-f MyJobs.yaml` would result in `MyJobs.json`. Similarly `MyJobs.epm.yaml` -> `MyJobs.epm.json`. (exact logic to be specified)
2. Provide a commandline flag to control the output file name. There currently is a flag `-o`, but its description is unclear and it does not seem to be addressing this requirement.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1033](https://github.com/eris-ltd/eris-cli/issues/1033) via [**ZenHub**](https://www.zenhub.com/)
