### ISSUE TITLE
[Core] eris pkgs do ... --contracts-path deletes the directory specified for --contracts-path upon failure

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#197]
This issue refers to the setup described in https://github.com/eris-ltd/eris-pm/issues/196

Upon encountering the error, the directory specified with the `--contracts-path` option is deleted.
This is a critical problem!

```
OSX version: 10.11.6
Eris CLI Version: 0.12.0-rc3
Docker:
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
docker-machine version 0.7.0, build a650a40
```

**Comment by VoR0220** [comment]
@zramsay @pietv Do you think you can take a look at this? It would appear that when the test is ran but it cannot find any contracts that it needs to find it winds up deleting the directory inside of it, I've been able to reproduce without quotes but with quotes I am unable. Can you take a look into this please?

**Comment by zramsay** [comment]
onit

**Comment by VoR0220** [comment]
This is going to be moved to CLI

**Comment by zramsay** [comment]
replaced by https://github.com/eris-ltd/eris-cli/issues/904 since this is on cli's level
Note: that #196 was confirmed as an issue for porcelain epm
