### ISSUE TITLE
[Core] Invoking functions of a library fails with "no return from contract"

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#198]
Linking libraries as tested in https://github.com/eris-ltd/eris-pm/tree/master/tests/fixtures/app35-library_handling is working.
However, when invoking a library's functions in a test function that has a return value, the EPM job after a while returns with nothing. See log output below.

The debug output (attached) reveals that the test function returned with "No return from contract" which seems almost like a timeout. The attached test reproduces this behavior.

[debug-log.txt](https://github.com/eris-ltd/eris-pm/files/428236/debug-log.txt)
[LibTest.zip](https://github.com/eris-ltd/eris-pm/files/428237/LibTest.zip)

```
eris pkgs do -c test -a CDB00407B6EDBF6735A88AA5B34FA24A8984D421 --local-compiler
Performing action. This can sometimes take a wee while.
Executing Job                                 defaultAddr
Executing Job                                 TestLib
Deploying Contract                       name=TestLibrary
                                         addr=A7BF2A5E539E9626EB4548E051E73755A756432D
Executing Job                                 PersonTest
Deploying Contract                       name=PersonTest
                                         addr=36ED65EB4EF09B52D9DE706A63FE625E7A8AAAA9
Executing Job                                 testNameChange
Executing Job                                 assertNameChange
Assertion Failed                               == success
assertion failed

Container interactive-86891928-a9b2-4ea7-bf8f-827874e4b43d exited with status 1
```

```
OSX version: 10.11.6
Eris CLI Version: 0.12.0-rc3
Docker:
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
docker-machine version 0.7.0, build a650a40
```

**Comment by VoR0220** [comment]
update on this. We have located and tracked down the core problem in this bug. It is a doozy but essentially one of the opcodes necessary for libraries is missing from the old tendermint branch (that opcode being delegatecall). I vote that we fix this by killing 2 birds with one stone and moving EPM to EDB while adding the missing delegate call into E-DB (It needs to be there anyway).

**Comment by VoR0220** [comment]
Closed per update of delegate call.
