### ISSUE TITLE
[Core] remove wait: true from required fields in epm.yaml

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-pm#199]
**Problem** -- it is ultra rare that on calls and most transactions that wait would be set to false. While there is a use case for that, it is far from the standard. At this time having `wait: true` as needed at all in the epm.yaml's is overkill and a line of code that users shouldn't need to type. 

**Solution** -- Set proper default of `wait: true` and remove all the waits from the fixtures.

**Comment by VoR0220** [comment]
Totally agree

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1029](https://github.com/eris-ltd/eris-cli/issues/1029) via [**ZenHub**](https://www.zenhub.com/)
