### ISSUE TITLE
[Core] export marshalling errors so folks can see why their epm.yaml didn't get parsed

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-pm#200]
**Problem** -- we squelch this error -> https://github.com/eris-ltd/eris-pm/blob/master/packages/load_package.go#L43 . In the past this was because viper had horrible error messages. No matter the quality of their error messages we need to export that error.

**Solution** -- refactor L43 in the form of L38

**Comment by VoR0220** [comment]
So has Viper gotten better to your knowledge? Either way i think this should be a doable fix.

**Comment by zramsay** [comment]
Yes, it has. Quite a bit. I've done this issue in CLI (unmerged errors branch)
