### ISSUE TITLE
[ABI] named inputs to functions should be populate-able as a struct

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-pm#201]
**Problem** -- when refactoring contracts, sometimes contract writers will shuffle their input arguments. Currently this would require a change in the array of the `data` field as well. However, this is nonsense, we know what the names of the arguments and what the job is trying to input.

**Solution** -- allow the `data` field to be a self-populating object which epm knows how to properly get packed. This will require changes to `PreProcessInputData` and/or `Pack/UnPack`.

**Comment by VoR0220** [comment]
Can you elaborate on this? Not sure i understand what you're getting at.

**Comment by compleatang** [comment]
this is a lot of work for very little gain upon reflection.
