### ISSUE TITLE
[Core] Consumption of Library Should not Require Instance

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#202]
Problem: While investigating #198 I discovered that if the instance of the consuming contract is not declared during deployment, an ABI error occurs and subsequent calls to the contract are not allowed. This should be fixed.

Solution: Investigate the problem more and report back here when more is found out.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1035](https://github.com/eris-ltd/eris-cli/issues/1035) via [**ZenHub**](https://www.zenhub.com/)
