### ISSUE TITLE
[Core] job: compile

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-pm#207]
**Problem** -- to support upcoming work on the library's team side we need to help them "package".

**Solution** -- step one is to provide a compile only job that will simply compile the file and save the binary. 

```go
type Compile struct {
  Contract string // can be a file or a directory
  Output string // can be nil (compile only, no write, good for stress testing compilers), a file, or a directory)
}
```

**Comment by VoR0220** [comment]
This is related to the lock file suggestion. It all ties into this.
