### ISSUE TITLE
eris pkgs do not returning a contract address

### ISSUE THREAD

**Issue by bsundar2** [eris-ltd/eris-pm#210]
Given the following files, I do not get a contract address and the `deployStorageK` field in epm.json is empty.

I was able to solve the problem and get the contract deployed by changing the contract name from ExampleContract to example, so that it would match the file name. Not sure if this is a Solidity constraint or not.

sample.sol:
```
contract sample {
  uint storedData;

  function set(uint x) {
    storedData = x;
  }

  function get() constant returns (uint retVal) {
    return storedData;
  }
}
```

example.sol:
```
import "./sample.sol";
contract ExampleContract is sample {
uint data;

  function set(uint x) {
    data = x;
  }

  function get() constant returns (uint retVal) {
    return data;
  }
}
```

epm.yaml:
```
jobs:

- name: deployStorageK
  job:
    deploy:
      contract: example.sol
      wait: true
```

The output from `eris pkgs do --chain simplechain --address $addr` is:
```
Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
Executing Job                                 deployStorageK
```

Versions:
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Eris CLI Version: 0.11.4

**Comment by VoR0220** [comment]
Did you get this solved in the slack? I think I saw your example before.

**Comment by bsundar2** [comment]
Yes, I got it solved. I have included how I solved it above. Zach asked me on slack to open an issue about the same so that other people can see it if they run into the same issue.

**Comment by VoR0220** [comment]
ah...do you mind making a suggestion to the docs? They should be in https://github.com/eris-ltd/eris-pm/tree/master/docs

**Comment by bsundar2** [comment]
Will do.
