### ISSUE TITLE
FR: Ability to control / influence EPM output to support bundles functions

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#214]
Flags and functionality for the EPM should be added to produce files that are targeted for further consumption.

Example: Previously deployed, registered contract and library addresses are needed further down in the installation routine of a multi-bundle deployment. By running .yaml files (install.yaml or upgrade.yaml contained in each bundle), the wiring of a series of bundles can be performed.

### Requirements
* EPM `do pkgs` should be able to produce a file with only the job output of contract deployments in a format that can be input as library file parameters to solc
* EPM needs a way to establish ENV variables that can be used in .yaml files. E.g. EPM could detect specially named files with variable settings that are pre-loaded before the actual .yaml executes.
* probably other ideas coming ...

**Comment by VoR0220** [comment]
This is why I was bringing up the lock file. This is related to that because that will enable us to keep track of our different previously deployed and registered contracts, and enable interaction between multiple deployments.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1024](https://github.com/eris-ltd/eris-cli/issues/1024) via [**ZenHub**](https://www.zenhub.com/)
