### ISSUE TITLE
[Core] Have Set Job Come from an empty interface

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-pm#241]
Problem: `true` sets to 1, not to bool value `true` and this causes confusion in our assert jobs. Small fry, but fixing this will enable a better UX. 

Other solution: Perhaps pass values instead into assert jobs and somehow assert that the values are the same? (might be more pain than it's worth).

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1022](https://github.com/eris-ltd/eris-cli/issues/1022) via [**ZenHub**](https://www.zenhub.com/)
