### ISSUE TITLE
Importing sol files changes the contract which gets deployed

### ISSUE THREAD

**Issue by nickzeeb** [eris-ltd/eris-pm#37]
I'm using eris version 0.11.0 on ubuntu 14.04.  When I try to deploy contract Two via the epm I get an assertion failure:

eris@erisbox:~/.eris/apps/idi$ eris contracts deploy --chain testChain
Performing Action. This can sometimes take a wee while.
Executing Job Named =>		account
Executing Job Named =>		one
Transaction Hash =>		EC2EDEF96B6CBB4CA632CBCAE3A80009DD1B356F
Executing Job Named =>		oneValue
Executing Job Named =>		assertOneValue
Assertion Failed =>		2:1
Container eris_interactive_eris_service_idi_tmp_deploy_1 exited with status 1

When I remove the import statement in two.sol it works fine:

eris@erisbox:~/.eris/apps/idi$ eris contracts deploy --chain testChain
Performing Action. This can sometimes take a wee while.
Executing Job Named =>		account
Executing Job Named =>		one
Transaction Hash =>		B84C0F223C8559F054AEACB97DADEA8C0CE1CE38
Executing Job Named =>		oneValue
Executing Job Named =>		assertOneValue

Counting the number of addresses on my blockchain shows that in both cases only one contract is actually deployed.

The assertion also succeeds if you swap the contract names.  Hence, looking at the assertion failure above shows that the import statement causes the alphabetically last contract (by name) to be the only contract that is deployed.

I think the correct fix here is not to deploy imported contracts.  Alternatively, you could offer the user the option to specify which contract should get deployed in the epm.yaml file.

[epm.yaml.txt](https://github.com/eris-ltd/eris-pm/files/58257/epm.yaml.txt)
[one.sol.txt](https://github.com/eris-ltd/eris-pm/files/58256/one.sol.txt)
[two.sol.txt](https://github.com/eris-ltd/eris-pm/files/58255/two.sol.txt)

**Comment by compleatang** [comment]
Will look into this tomorrow. I suspect it is a matter of how the solidity compiler handles imports / inheritance but will have a more solid answer tomorrow.

**Comment by compleatang** [comment]
this is a tricky one. still investigating whether it is how we're compiling or how solidity compiler is working.

**Comment by compleatang** [comment]
will be fixed in 0.11.3
