### ISSUE TITLE
assertions on zero values always fail

### ISSUE THREAD

**Issue by SatoshiiNakamoto** [eris-ltd/eris-pm#39]
when I try to deploy the attached Zero.sol contract with the attached epm.yaml file I get this output:

$ eris contracts deploy --chain test
Performing Action. This can sometimes take a wee while.
Executing Job Named =>		account
Executing Job Named =>		contract
Contract Address =>		1A520489ECD1023588FCB9DDF74B23838BF99DD6
Executing Job Named =>		query
Return Value =>			
Executing Job Named =>		assertZero
Assertion Failed =>		:0
	[]:[48]
Container eris_interactive_eris_service_zeroBug_tmp_deploy_1 exited with status 1

this shows 2 bugs:
1. The "Return Value =>" output line is not showing the value "0"
2. The assertion fails

versions:
$ eris version
Eris CLI Version: 0.11.0

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

[Zero.sol.txt](https://github.com/eris-ltd/eris-pm/files/62369/Zero.sol.txt)
[epm.yaml.txt](https://github.com/eris-ltd/eris-pm/files/62370/epm.yaml.txt)

**Comment by compleatang** [comment]
Thanks! Will add a test for this and look into it tomorrow.

**Comment by compleatang** [comment]
Found the problem. Was interpreting all `0` returns from the contract as an empty string in our decoder. Just testing the fix now. To update use go get or `docker pull quay.io/eris/epm:0.11.0` any time after about 20 mins from now.

**Comment by compleatang** [comment]
fixed on master. closing now. let me know if it doesn't work for you but have added this as a test going forward so should not have any more problems. Thank you for the report!

**Comment by SatoshiiNakamoto** [comment]
Great thanks! I can confirm that the bug is fixed now.
