### ISSUE TITLE
More Intuitive Way to Send Transactions

### ISSUE THREAD

**Issue by crainbf** [eris-ltd/eris-pm#41]
Currently, the way one can use epm to send a transaction to a contract is extremely unintuitive. Nobody will think of using 'eris contracts deploy' to send transactions. At the same time, during development you need to be able to send transactions to contracts using epm.

**Comment by crainbf** [comment]
It might even be enough to change this to 'eris send tx' instead of eris contracts deploy. After all, deploying contracts is a subset of transactions being sent, but a send transaction is not a subset of a contract deployment. It might not be intuitive to everyone that you deploy a contract by sending a transaction, but that's actually something people need to understand conceptually anyway so that would be okay.

**Comment by compleatang** [comment]
i am partial to `eris pkg do` which would be neutral as to the pkg was about tx or was about contracts...

**Comment by crainbf** [comment]
I think that would be much better. What about `eris pkg send`? I like being clear that you are really sending data to the chain and the rest is done there.

**Comment by compleatang** [comment]
OK. Am going to close this issue here as it really belongs in eris-cli repo -> https://github.com/eris-ltd/eris-cli/issues/405
