### ISSUE TITLE
Unrecognized return type string

### ISSUE THREAD

**Issue by SatoshiiNakamoto** [eris-ltd/eris-pm#44]
$ eris contracts deploy --chain test
Performing Action. This can sometimes take a wee while.
Executing Job Named =>		account
Executing Job Named =>		contract
Contract Address =>		B0DB8DFE7F6D90BF3FB8CD47834C8C1BA908B880
Executing Job Named =>		query
Unrecognized return type
Container eris_interactive_eris_service_stringsBug_tmp_deploy_1 exited with status 1

files:
[epm.yaml.txt](https://github.com/eris-ltd/eris-pm/files/71020/epm.yaml.txt)
[Strings.sol.txt](https://github.com/eris-ltd/eris-pm/files/71021/Strings.sol.txt)

versions:
$ eris version
Eris CLI Version: 0.11.0

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.3 LTS
Release: 14.04
Codename: trusty

**Comment by compleatang** [comment]
thanks. this is a known issue (see #35). for now we recommend not using solidity's string types and rather using byte arrays as they are more stable and usable. Will try to get a fix pushed very soon.

**Comment by SatoshiiNakamoto** [comment]
Great, thanks!

**Comment by palutz** [comment]
Hi,
any example how to do it and also how to run the web interface to read and write (so instead the simple example with int to do the same, get and set of a value, but with bytes array/string). 
Sorry but all the documentation links looks broken (Jobs specification and Variable Specification).

**Comment by compleatang** [comment]
Will fix the links in the readme, but everything is available here -> https://docs.erisindustries.com/documentation/

Yes. we have examples in the tests/fixtures folder for how to work with different variable types. 

In our tutorials (https://docs.erisindustries.com/tutorials/) we have super simple node.js application very similar in nature to the epm.yaml on the readme.

**Comment by palutz** [comment]
Thanks.
The problem is that the example provided is not working anymore with the bytes type. So you need to modify also the web applcication

After some tests I modified the example like this:
https://gist.github.com/palutz/6da3cadc93dfc22ef651

Is that correct?

**Comment by compleatang** [comment]
Looks good. Will try to test later this evening. If it would be helpful, we can make little examples for working with the rest of Solidity types and put them in our tutorials. Let me know if that is something which would help you get up to speed quickly and we'll action it.

BTW, am assuming by example you mean the one from the contracts interacting tutorial..?

**Comment by palutz** [comment]
Yes, I do. 
Sorry if I wasn't enough clear about.

**Comment by compleatang** [comment]
Great. Will give a test and try to work up something which gets to the other types....

**Comment by compleatang** [comment]
strings now fully supported and tested for 0.11.3 release
