### ISSUE TITLE
negative int arguments are interpreted as zero

### ISSUE THREAD

**Issue by SatoshiiNakamoto** [eris-ltd/eris-pm#45]
$ eris contracts deploy --chain test
Performing Action. This can sometimes take a wee while.
Executing Job Named =>		account
Executing Job Named =>		contract
Contract Address =>		36753FE769B6C506CBF4857E08A0A7B79DFD11DA
Executing Job Named =>		value
Return Value =>			0
Executing Job Named =>		assert
Assertion Failed =>		0:-1
	[48]:[45 49]
Container eris_interactive_eris_service_negativeNumbersBug_tmp_deploy_1 exited with status 1

files:
[Contract.sol.txt](https://github.com/eris-ltd/eris-pm/files/71054/Contract.sol.txt)
[epm.yaml.txt](https://github.com/eris-ltd/eris-pm/files/71055/epm.yaml.txt)

versions:
$ eris version
Eris CLI Version: 0.11.0

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.3 LTS
Release: 14.04
Codename: trusty

**Comment by compleatang** [comment]
great. just fixed this and added a test to make sure it stays fixed. thanks so much for the reporting!

**Comment by SatoshiiNakamoto** [comment]
great, thanks!
