### ISSUE TITLE
Unrecognized return type bytes

### ISSUE THREAD

**Issue by SatoshiiNakamoto** [eris-ltd/eris-pm#46]
$ eris contracts deploy --chain test
Performing Action. This can sometimes take a wee while.
Executing Job Named =>		account
Executing Job Named =>		contract
Contract Address =>		09AB1B0034774D5EE9783BC4543C1F9B2B875760
Executing Job Named =>		value
Unrecognized return type
Container eris_interactive_eris_service_bytesBug_tmp_deploy_1 exited with status 1

files:
[Contract.sol.txt](https://github.com/eris-ltd/eris-pm/files/71111/Contract.sol.txt)
[epm.yaml.txt](https://github.com/eris-ltd/eris-pm/files/71112/epm.yaml.txt)

versions:
$ eris version
Eris CLI Version: 0.11.0

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.3 LTS
Release: 14.04
Codename: trusty

**Comment by compleatang** [comment]
try `bytes32`... I will keep working thru rest of the types.

**Comment by SatoshiiNakamoto** [comment]
thanks, yes bytes32 works well

**Comment by compleatang** [comment]
great. typecasting in go is notoriously difficult but definitely thanks for helping to test! working on the negative ints now and will get to all of the byte types and strings later this week I hope.

**Comment by SatoshiiNakamoto** [comment]
great! glad to help

**Comment by compleatang** [comment]
strings and bytes types now working and fully tested for 0.11.3 release.
