### ISSUE TITLE
add dump-state to jobs

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-pm#5]
use mint-dump

**Comment by ebuchman** [comment]
this won't work nicely. mint-dump currently requires the node to be off since it loads the db to dump it. we'd have to expose it as an rpc command

**Comment by compleatang** [comment]
couldn't we just turn the node off as it is and then run mint-dump against that data-dir?

**Comment by ebuchman** [comment]
sure. its just a major deviation from how any other commands in the system might work

**Comment by compleatang** [comment]
fair. could also handle at the cli level (which would probably be nicer)?

**Comment by ebuchman** [comment]
ya might be better. its more a chain mgmt thing so not sure it belongs in the pm

**Comment by compleatang** [comment]
k.
