### ISSUE TITLE
Bytes32 value truncate the value stored. Is there a limit?

### ISSUE THREAD

**Issue by palutz** [eris-ltd/eris-pm#55]
Hi,
I have a really simple contract (not ideal but just to try to store a small stream of data):

```
mapping (int => bytes32) storedData;

  function SimpleStorage() {
    numData = 0;
  }

  function set(uint nonce, bytes32 msg) {
    numData = numData + 1;
    storedData[numData] = msg;
  }

  function getLength() constant returns (int) {
    return numData;
  }

  function get(int nonce) constant returns (bytes32 retVal) {
    return storedData[nonce];
  }
```

But everytime I get the value back from the app, the string it's truncated. I put something like 200 characters or more but I'm always getting no more than 10-20 chars back.
Is it normal? Should I use another type and if so, which one?

Thanks,
Stefano

**Comment by dennismckinnon** [comment]
Hello Stefano,

I believe your problem to be that you are using the bytes32 type to store information. The bytes32 object can store at most 32 bytes. If you would rather store a string of indeterminate length you should use the string object.

Creating a mapping of bytes32 objects does not allow automatic assignment to more then one element of the mapping.

As to why 10-20 characters back I guess that depends on if your string contains any multi-byte characters. Most characters are a single byte but thats not the case for ALL characters.

I hope this helped clarify what is likely the culprit of your confusion. For more information you can refer to the solidity documentation here: http://solidity.readthedocs.org/en/latest/

**Comment by palutz** [comment]
Hi,
thanks. Yes I'm using the byte32 to store.
It looks like the string is not working properly yet (if you take a look at the other issues).
I will try in another way so far, thanks.

PS: I tried with bytes too but is the same problem.

**Comment by compleatang** [comment]
closing for now. strings are being worked on. we are aiming for 0.11.3
