### ISSUE TITLE
Support testing of contracts created 'in-flight' during a test (contract factory pattern)

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#58]
Currently, when testing via epm.yaml the "deploy" job compiles the specified contract and stores the ABI under the account address of that contract instance (e.g. /abi/81796575E8FA80FF34518989BC70567E32862D37)
When subsequently a contract is created on-the-fly via a contract factory function, it is not possible to interact with that contract instance from epm. To be precise: it is already possible to call a function on a factory contract and return the address of the newly created contract which is then available as variable in epm to subsequent jobs. However, calling functions of that contract fails due to the ABI not being found in the 'abi' folder.

## Requirements
Support interaction with contracts that were not deployed actively from epm, but created during the test.

**Comment by compleatang** [comment]
will ship in 0.11.3
