### ISSUE TITLE
single job command line input

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-pm#62]
Old epm had a way to do single jobs/commands from command line. this was a popular feature as it gave a very interactive and direct connection to the smart contract object which was excellent for learning , debugging those weird bugs and general fun.

Low priority but it would be nice to re-expose command line access to start single jobs so users can take advantage of all the power behind epm and epm.yamls in a free forming style.

**Comment by compleatang** [comment]
you've won me over @dennismckinnon

**Comment by compleatang** [comment]
closing for now. we can revisit this as actions if necessary.
