### ISSUE TITLE
Support multiple return values of contract function calls

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#63]
Calling a function that has multiple return values (e.g. function get() returns (uint, address, bytes32) {}) only stores the first value in the $jobname variable. It should be possible to access all return values.

## Functionality
- If there is only one return value, the behavior stays as is for convenience reasons and backwards compatibility
- If there are multiple return values they should be accessible via index, e.g. $jobname[2]

**Comment by dennismckinnon** [comment]
Would also be nice to have them accessible via name of the return variable

$jobname.returnVarName

as per the abi spec.

**Comment by compleatang** [comment]
Will handle tuples in 0.11.4

**Comment by compleatang** [comment]
test:

```js
function getStatus() returns (uint, uint) {
  return (1, 2);
}
```

**Comment by compleatang** [comment]
also need to test multiple dynamic returns:

```javascript
function getStrings() returns (string, string) {
  return string1, string2;
}
````
