### ISSUE TITLE
Transaction call should give acces to return values

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#64]
Currently, when executing a TX call, the value that gets stored in the $jobname variable in epm is the transaction hash and there is no capability of accessing the return values of the function call.

## Functionality
- Align the behavior of storing return values of TX calls to that suggested in ticket #63
- Provide access to the transaction hash, e.g. via $jobname['txhash'] or similar field access

**Comment by compleatang** [comment]
Expected behaviour moving forward:

return value by default is stored as the job result unless a field:

```yaml
save: tx
```

is added to the `call` in which case the txHash will be saved instead of the return from the contract.
