### ISSUE TITLE
query-contract

### ISSUE THREAD

**Issue by ochang19** [eris-ltd/eris-pm#65]
'query-contract' doesn't work properly
I set 'destination' value 'Contract Address'
But it returns error msg like 
'Account 11111111111111111111111111111111111111 does not exist

Please check about that.

**Comment by compleatang** [comment]
@ochang19 this ticket doesn't really tell us much. Is 'Contract Address' a variable you are using? Please provide a sample epm.yaml and / or the debug output from the command and we would be happy to assist your efforts.

**Comment by ochang19** [comment]
I'm just talking about QueryContract Jobs
---------------------------------------------------------------------------
type QueryContract struct {
  // (Optional, if account job or global account set) address of the account from which to send (the
  // public key for the account must be available to eris-keys)
  Source string `mapstructure:"source" json:"source" yaml:"source" toml:"source"`
  // (Required) address of the contract which should be called
  Destination string `mapstructure:"destination" json:"destination" yaml:"destination" toml:"destination"`
  // (Required) data which should be called. will use the eris-abi tooling under the hood to formalize the
  // transaction. QueryContract will usually be used with "accessor" functions in contracts
  Data string `mapstructure:"data" json:"data" yaml:"data" toml:"data"`
}
------------------------------------------------------------------------------------------------
I wrote epm.yaml like follows(I'm on tutorial 'Deploying your Smart Contracts to a Chain')

- name: queryStorage
  job:
    query-contract:
      destination: E463D4A8EC6D0050A4DFCC16190CA7650E9764AD
      data: get

E463D4A8EC6D0050A4DFCC16190CA7650E9764AD is contract address created by 'Deploy' Job

when I execute epm.yaml by 'eris pkgs do .....'

it tells 'Account E463D4A8EC6D0050A4DFCC16190CA7650E9764AD does not exist'

**Comment by compleatang** [comment]
@ochang19 just checking that this issue is fixed for you now?
