### ISSUE TITLE
Having a folder with npm modules in a .eris/apps/chainname folder prevents pkgs do

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/eris-pm#67]
/home/pvkooten/.eris/apps/aaa $ ls

shows files

    abi  account.json  epm.json  epm.yaml  idi.sol  serverapp

And 

    pvkooten@prftrd:~/.eris/apps/aaa/serverapp$ ls

shows 

    app.js  node_modules  package.json

Using

    pvkooten@prftrd:~/.eris/apps/aaa$ eris pkgs do --chain aaa --address $addr

yields error:

    API error (500): Cannot start container eris_interactive_eris_service_aaa_tmp_deploy_1: [8] System error: no such file or directory

When moving the `serverapps` folder away, `pkgs do` does work!

**Comment by compleatang** [comment]
this should be fixed in 0.11.3
