### ISSUE TITLE
Improve error message for missing parameter '-c' in pkgs do

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#81]
When running an epm script with 'eris pkgs do' and not specifying the chain parameter '-c' the user is presented with a confusing error:
`Error moving keys: API error (500): Cannot link to a non running container: /eris_chain_contracts_de1ce4ac_1 AS /eris_interactive_eris_chain_contracts_de1ce4ac_1/chain`

`-c` or `--chain` is a mandatory parameter and leaving it out should result in immediate "usage" error.

**Comment by compleatang** [comment]
closing here. this is a cli issue.
